#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx
  - git
  - mysql-client
  - curl
  - build-essential
  - nginx

runcmd:
  - |
    # Install Node.js 18
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    apt-get install -y nodejs npm
    # Install Docker from Ubuntu repository
    sudo apt-get update -y
    sudo apt-get install -y docker.io
    # Enable and start Docker
    sudo systemctl enable docker
    sudo systemctl start docker
    # Add ubuntu user to docker group
    sudo usermod -aG docker ubuntu || true
    # Fix permissions on docker.sock (prevents PermissionError)
    sudo chown root:docker /var/run/docker.sock
    sudo chown root:docker /var/run/docker.sock
    # Install Docker Compose v2 (docker compose plugin)
    mkdir -p /usr/lib/docker/cli-plugins
    curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/lib/docker/cli-plugins/docker-compose
    sudo chmod +x /usr/lib/docker/cli-plugins/docker-compose
    sudo apt  install docker-compose -y
    sudo systemctl restart docker
    # Verify docker and compose installation
    docker --version
    docker-compose version

    