ami_id         = "ami-0ecb62995f68bb549"
key_name       = "id_rsa"
public_key_path  = "~/.ssh/id_rsa.pub"
private_key_path = "~/.ssh/id_rsa"
domain         = "kolawole.chickenkiller.com"
acme_email     = "okolawoles36@gmail.com"
github_repo    = "https://github.com/okekolawolesunday009/DevOps-Stage-6.git"
